In [1]:
import numpy as np

In [2]:
x = np.random.rand(2, 3, 2)

In [3]:
x

array([[[0.31231281, 0.76294917],
        [0.70168791, 0.3182975 ],
        [0.54000288, 0.74688783]],

       [[0.23972892, 0.10881745],
        [0.655023  , 0.69217796],
        [0.0481949 , 0.80526388]]])

In [4]:
x.reshape(1, -1)

array([[0.31231281, 0.76294917, 0.70168791, 0.3182975 , 0.54000288,
        0.74688783, 0.23972892, 0.10881745, 0.655023  , 0.69217796,
        0.0481949 , 0.80526388]])

In [7]:
arr = np.array([1, 2, 1, 2, 1, 3, 4, 4, 5])

In [8]:
np.unique(arr, return_counts=True)

(array([1, 2, 3, 4, 5]), array([3, 2, 1, 2, 1], dtype=int64))

In [10]:
arr = np.array([[2, 3, 4], [1, 5, 7]])
arr

array([[2, 3, 4],
       [1, 5, 7]])

In [11]:
np.reshape(arr, (3, 2))

array([[2, 3],
       [4, 1],
       [5, 7]])

In [12]:
arr.T

array([[2, 1],
       [3, 5],
       [4, 7]])

In [13]:
a = {3: '3', 2: '2', -10: 's'}

In [14]:
sorted(a)

[-10, 2, 3]

In [15]:
it = iter(a)

In [18]:
dir(it)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__length_hint__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [19]:
it.__next__()

3